// Generated by scripts/build-registry.mjs. Do not edit.
import type { ComponentType } from "react";
import E0 from "@/registry/lantern/examples/ambient-demo";
import E1 from "@/registry/lantern/examples/ambient-positions";
import E2 from "@/registry/lantern/examples/code-block-demo";
import E3 from "@/registry/lantern/examples/code-block-line-numbers";
import E4 from "@/registry/lantern/examples/code-block-max-height";
import E5 from "@/registry/lantern/examples/command-tabs-demo";
import E6 from "@/registry/lantern/examples/command-tabs-install";
import E7 from "@/registry/lantern/examples/console-demo";
import E8 from "@/registry/lantern/examples/control-pad-demo";
import E9 from "@/registry/lantern/examples/control-pad-compact";
import E10 from "@/registry/lantern/examples/directory-card-demo";
import E11 from "@/registry/lantern/examples/directory-card-grid";
import E12 from "@/registry/lantern/examples/eyebrow-demo";
import E13 from "@/registry/lantern/examples/guestbook-demo";
import E14 from "@/registry/lantern/examples/guestbook-read-only";
import E15 from "@/registry/lantern/examples/inventory-grid-demo";
import E16 from "@/registry/lantern/examples/inventory-grid-chest";
import E17 from "@/registry/lantern/examples/key-reveal-demo";
import E18 from "@/registry/lantern/examples/key-reveal-masked";
import E19 from "@/registry/lantern/examples/navbar-demo";
import E20 from "@/registry/lantern/examples/orbit-demo";
import E21 from "@/registry/lantern/examples/orbit-spin";
import E22 from "@/registry/lantern/examples/orbit-custom";
import E23 from "@/registry/lantern/examples/server-card-demo";
import E24 from "@/registry/lantern/examples/server-card-offline";
import E25 from "@/registry/lantern/examples/server-card-grid";
import E26 from "@/registry/lantern/examples/stat-demo";
import E27 from "@/registry/lantern/examples/status-dot-demo";
import E28 from "@/registry/lantern/examples/status-pill-demo";
import E29 from "@/registry/lantern/examples/status-pill-list";
import E30 from "@/registry/lantern/examples/terminal-demo";
import E31 from "@/registry/lantern/examples/typewriter-demo";
import E32 from "@/registry/lantern/examples/typewriter-standalone";
import E33 from "@/registry/lantern/examples/button-demo";
import E34 from "@/registry/lantern/examples/button-variants";
import E35 from "@/registry/lantern/examples/button-sizes";
import E36 from "@/registry/lantern/examples/button-states";
import E37 from "@/registry/lantern/examples/button-group-demo";
import E38 from "@/registry/lantern/examples/button-group-input";
import E39 from "@/registry/lantern/examples/button-group-split";
import E40 from "@/registry/lantern/examples/calendar-demo";
import E41 from "@/registry/lantern/examples/calendar-range";
import E42 from "@/registry/lantern/examples/calendar-dropdown";
import E43 from "@/registry/lantern/examples/checkbox-demo";
import E44 from "@/registry/lantern/examples/checkbox-disabled";
import E45 from "@/registry/lantern/examples/checkbox-checklist";
import E46 from "@/registry/lantern/examples/combobox-demo";
import E47 from "@/registry/lantern/examples/combobox-multi";
import E48 from "@/registry/lantern/examples/combobox-form";
import E49 from "@/registry/lantern/examples/copy-button-demo";
import E50 from "@/registry/lantern/examples/copy-button-input";
import E51 from "@/registry/lantern/examples/date-picker-demo";
import E52 from "@/registry/lantern/examples/date-picker-range";
import E53 from "@/registry/lantern/examples/date-picker-presets";
import E54 from "@/registry/lantern/examples/field-demo";
import E55 from "@/registry/lantern/examples/field-login";
import E56 from "@/registry/lantern/examples/field-signup";
import E57 from "@/registry/lantern/examples/field-settings";
import E58 from "@/registry/lantern/examples/field-contact";
import E59 from "@/registry/lantern/examples/field-newsletter";
import E60 from "@/registry/lantern/examples/form-demo";
import E61 from "@/registry/lantern/examples/form-controls";
import E62 from "@/registry/lantern/examples/input-demo";
import E63 from "@/registry/lantern/examples/input-types";
import E64 from "@/registry/lantern/examples/input-group-demo";
import E65 from "@/registry/lantern/examples/input-group-affixes";
import E66 from "@/registry/lantern/examples/input-group-button";
import E67 from "@/registry/lantern/examples/input-otp-demo";
import E68 from "@/registry/lantern/examples/input-otp-separator";
import E69 from "@/registry/lantern/examples/label-demo";
import E70 from "@/registry/lantern/examples/native-select-demo";
import E71 from "@/registry/lantern/examples/native-select-groups";
import E72 from "@/registry/lantern/examples/native-select-states";
import E73 from "@/registry/lantern/examples/radio-group-demo";
import E74 from "@/registry/lantern/examples/radio-group-cards";
import E75 from "@/registry/lantern/examples/select-demo";
import E76 from "@/registry/lantern/examples/select-grouped";
import E77 from "@/registry/lantern/examples/select-states";
import E78 from "@/registry/lantern/examples/slider-demo";
import E79 from "@/registry/lantern/examples/slider-range";
import E80 from "@/registry/lantern/examples/switch-demo";
import E81 from "@/registry/lantern/examples/switch-settings";
import E82 from "@/registry/lantern/examples/tag-input-demo";
import E83 from "@/registry/lantern/examples/tag-input-max";
import E84 from "@/registry/lantern/examples/textarea-demo";
import E85 from "@/registry/lantern/examples/textarea-states";
import E86 from "@/registry/lantern/examples/toggle-demo";
import E87 from "@/registry/lantern/examples/toggle-outline";
import E88 from "@/registry/lantern/examples/toggle-text";
import E89 from "@/registry/lantern/examples/toggle-group-demo";
import E90 from "@/registry/lantern/examples/toggle-group-multiple";
import E91 from "@/registry/lantern/examples/accordion-demo";
import E92 from "@/registry/lantern/examples/aspect-ratio-demo";
import E93 from "@/registry/lantern/examples/aspect-ratio-square";
import E94 from "@/registry/lantern/examples/avatar-demo";
import E95 from "@/registry/lantern/examples/avatar-fallback";
import E96 from "@/registry/lantern/examples/avatar-group";
import E97 from "@/registry/lantern/examples/badge-demo";
import E98 from "@/registry/lantern/examples/card-demo";
import E99 from "@/registry/lantern/examples/card-art";
import E100 from "@/registry/lantern/examples/carousel-demo";
import E101 from "@/registry/lantern/examples/carousel-sizes";
import E102 from "@/registry/lantern/examples/carousel-vertical";
import E103 from "@/registry/lantern/examples/item-demo";
import E104 from "@/registry/lantern/examples/item-link";
import E105 from "@/registry/lantern/examples/item-avatar";
import E106 from "@/registry/lantern/examples/kbd-demo";
import E107 from "@/registry/lantern/examples/separator-demo";
import E108 from "@/registry/lantern/examples/table-demo";
import E109 from "@/registry/lantern/examples/table-compact";
import E110 from "@/registry/lantern/examples/timeline-demo";
import E111 from "@/registry/lantern/examples/timeline-compact";
import E112 from "@/registry/lantern/examples/typography-demo";
import E113 from "@/registry/lantern/examples/typography-prose";
import E114 from "@/registry/lantern/examples/chart-demo";
import E115 from "@/registry/lantern/examples/chart-bar";
import E116 from "@/registry/lantern/examples/chart-line";
import E117 from "@/registry/lantern/examples/chart-donut";
import E118 from "@/registry/lantern/examples/chart-radial";
import E119 from "@/registry/lantern/examples/data-table-demo";
import E120 from "@/registry/lantern/examples/data-table-minimal";
import E121 from "@/registry/lantern/examples/collapsible-demo";
import E122 from "@/registry/lantern/examples/collapsible-file-tree";
import E123 from "@/registry/lantern/examples/direction-demo";
import E124 from "@/registry/lantern/examples/drawer-demo";
import E125 from "@/registry/lantern/examples/drawer-responsive";
import E126 from "@/registry/lantern/examples/resizable-demo";
import E127 from "@/registry/lantern/examples/resizable-vertical";
import E128 from "@/registry/lantern/examples/resizable-editor";
import E129 from "@/registry/lantern/examples/scroll-area-demo";
import E130 from "@/registry/lantern/examples/scroll-area-horizontal";
import E131 from "@/registry/lantern/examples/sidebar-demo";
import E132 from "@/registry/lantern/examples/sidebar-icon";
import E133 from "@/registry/lantern/examples/sidebar-floating";
import E134 from "@/registry/lantern/examples/alert-dialog-demo";
import E135 from "@/registry/lantern/examples/context-menu-demo";
import E136 from "@/registry/lantern/examples/dialog-demo";
import E137 from "@/registry/lantern/examples/dialog-scrollable";
import E138 from "@/registry/lantern/examples/dropdown-menu-demo";
import E139 from "@/registry/lantern/examples/dropdown-menu-checkboxes";
import E140 from "@/registry/lantern/examples/dropdown-menu-radio-group";
import E141 from "@/registry/lantern/examples/hover-card-demo";
import E142 from "@/registry/lantern/examples/popover-demo";
import E143 from "@/registry/lantern/examples/sheet-demo";
import E144 from "@/registry/lantern/examples/sheet-sides";
import E145 from "@/registry/lantern/examples/tooltip-demo";
import E146 from "@/registry/lantern/examples/breadcrumb-demo";
import E147 from "@/registry/lantern/examples/breadcrumb-dropdown";
import E148 from "@/registry/lantern/examples/command-demo";
import E149 from "@/registry/lantern/examples/command-dialog";
import E150 from "@/registry/lantern/examples/file-tree-demo";
import E151 from "@/registry/lantern/examples/file-tree-selection";
import E152 from "@/registry/lantern/examples/menubar-demo";
import E153 from "@/registry/lantern/examples/navigation-menu-demo";
import E154 from "@/registry/lantern/examples/pagination-demo";
import E155 from "@/registry/lantern/examples/stepper-demo";
import E156 from "@/registry/lantern/examples/stepper-horizontal";
import E157 from "@/registry/lantern/examples/tabs-demo";
import E158 from "@/registry/lantern/examples/tabs-boxed";
import E159 from "@/registry/lantern/examples/alert-demo";
import E160 from "@/registry/lantern/examples/alert-variants";
import E161 from "@/registry/lantern/examples/announcement-bar-demo";
import E162 from "@/registry/lantern/examples/announcement-bar-variants";
import E163 from "@/registry/lantern/examples/empty-demo";
import E164 from "@/registry/lantern/examples/progress-demo";
import E165 from "@/registry/lantern/examples/progress-labeled";
import E166 from "@/registry/lantern/examples/skeleton-demo";
import E167 from "@/registry/lantern/examples/sonner-demo";
import E168 from "@/registry/lantern/examples/spinner-demo";
import E169 from "@/registry/lantern/examples/spinner-button";
import E170 from "@/registry/lantern/examples/attachment-demo";
import E171 from "@/registry/lantern/examples/attachment-states";
import E172 from "@/registry/lantern/examples/bubble-demo";
import E173 from "@/registry/lantern/examples/bubble-variants";
import E174 from "@/registry/lantern/examples/bubble-reactions";
import E175 from "@/registry/lantern/examples/marker-demo";
import E176 from "@/registry/lantern/examples/message-demo";
import E177 from "@/registry/lantern/examples/message-scroller-demo";
import B0 from "@/registry/lantern/blocks/dashboard/dashboard";
import B1 from "@/registry/lantern/blocks/docs-layout/docs-layout";
import B2 from "@/registry/lantern/blocks/faq/faq";
import B3 from "@/registry/lantern/blocks/feature-grid/feature-grid";
import B4 from "@/registry/lantern/blocks/footer/footer";
import B5 from "@/registry/lantern/blocks/hero/hero";
import B6 from "@/registry/lantern/blocks/login/login";
import B7 from "@/registry/lantern/blocks/not-found/not-found";
import B8 from "@/registry/lantern/blocks/pricing/pricing";
import B9 from "@/registry/lantern/blocks/settings/settings";
import B10 from "@/registry/lantern/blocks/signup/signup";

export const examples: Record<string, ComponentType> = {
  "ambient-demo": E0,
  "ambient-positions": E1,
  "code-block-demo": E2,
  "code-block-line-numbers": E3,
  "code-block-max-height": E4,
  "command-tabs-demo": E5,
  "command-tabs-install": E6,
  "console-demo": E7,
  "control-pad-demo": E8,
  "control-pad-compact": E9,
  "directory-card-demo": E10,
  "directory-card-grid": E11,
  "eyebrow-demo": E12,
  "guestbook-demo": E13,
  "guestbook-read-only": E14,
  "inventory-grid-demo": E15,
  "inventory-grid-chest": E16,
  "key-reveal-demo": E17,
  "key-reveal-masked": E18,
  "navbar-demo": E19,
  "orbit-demo": E20,
  "orbit-spin": E21,
  "orbit-custom": E22,
  "server-card-demo": E23,
  "server-card-offline": E24,
  "server-card-grid": E25,
  "stat-demo": E26,
  "status-dot-demo": E27,
  "status-pill-demo": E28,
  "status-pill-list": E29,
  "terminal-demo": E30,
  "typewriter-demo": E31,
  "typewriter-standalone": E32,
  "button-demo": E33,
  "button-variants": E34,
  "button-sizes": E35,
  "button-states": E36,
  "button-group-demo": E37,
  "button-group-input": E38,
  "button-group-split": E39,
  "calendar-demo": E40,
  "calendar-range": E41,
  "calendar-dropdown": E42,
  "checkbox-demo": E43,
  "checkbox-disabled": E44,
  "checkbox-checklist": E45,
  "combobox-demo": E46,
  "combobox-multi": E47,
  "combobox-form": E48,
  "copy-button-demo": E49,
  "copy-button-input": E50,
  "date-picker-demo": E51,
  "date-picker-range": E52,
  "date-picker-presets": E53,
  "field-demo": E54,
  "field-login": E55,
  "field-signup": E56,
  "field-settings": E57,
  "field-contact": E58,
  "field-newsletter": E59,
  "form-demo": E60,
  "form-controls": E61,
  "input-demo": E62,
  "input-types": E63,
  "input-group-demo": E64,
  "input-group-affixes": E65,
  "input-group-button": E66,
  "input-otp-demo": E67,
  "input-otp-separator": E68,
  "label-demo": E69,
  "native-select-demo": E70,
  "native-select-groups": E71,
  "native-select-states": E72,
  "radio-group-demo": E73,
  "radio-group-cards": E74,
  "select-demo": E75,
  "select-grouped": E76,
  "select-states": E77,
  "slider-demo": E78,
  "slider-range": E79,
  "switch-demo": E80,
  "switch-settings": E81,
  "tag-input-demo": E82,
  "tag-input-max": E83,
  "textarea-demo": E84,
  "textarea-states": E85,
  "toggle-demo": E86,
  "toggle-outline": E87,
  "toggle-text": E88,
  "toggle-group-demo": E89,
  "toggle-group-multiple": E90,
  "accordion-demo": E91,
  "aspect-ratio-demo": E92,
  "aspect-ratio-square": E93,
  "avatar-demo": E94,
  "avatar-fallback": E95,
  "avatar-group": E96,
  "badge-demo": E97,
  "card-demo": E98,
  "card-art": E99,
  "carousel-demo": E100,
  "carousel-sizes": E101,
  "carousel-vertical": E102,
  "item-demo": E103,
  "item-link": E104,
  "item-avatar": E105,
  "kbd-demo": E106,
  "separator-demo": E107,
  "table-demo": E108,
  "table-compact": E109,
  "timeline-demo": E110,
  "timeline-compact": E111,
  "typography-demo": E112,
  "typography-prose": E113,
  "chart-demo": E114,
  "chart-bar": E115,
  "chart-line": E116,
  "chart-donut": E117,
  "chart-radial": E118,
  "data-table-demo": E119,
  "data-table-minimal": E120,
  "collapsible-demo": E121,
  "collapsible-file-tree": E122,
  "direction-demo": E123,
  "drawer-demo": E124,
  "drawer-responsive": E125,
  "resizable-demo": E126,
  "resizable-vertical": E127,
  "resizable-editor": E128,
  "scroll-area-demo": E129,
  "scroll-area-horizontal": E130,
  "sidebar-demo": E131,
  "sidebar-icon": E132,
  "sidebar-floating": E133,
  "alert-dialog-demo": E134,
  "context-menu-demo": E135,
  "dialog-demo": E136,
  "dialog-scrollable": E137,
  "dropdown-menu-demo": E138,
  "dropdown-menu-checkboxes": E139,
  "dropdown-menu-radio-group": E140,
  "hover-card-demo": E141,
  "popover-demo": E142,
  "sheet-demo": E143,
  "sheet-sides": E144,
  "tooltip-demo": E145,
  "breadcrumb-demo": E146,
  "breadcrumb-dropdown": E147,
  "command-demo": E148,
  "command-dialog": E149,
  "file-tree-demo": E150,
  "file-tree-selection": E151,
  "menubar-demo": E152,
  "navigation-menu-demo": E153,
  "pagination-demo": E154,
  "stepper-demo": E155,
  "stepper-horizontal": E156,
  "tabs-demo": E157,
  "tabs-boxed": E158,
  "alert-demo": E159,
  "alert-variants": E160,
  "announcement-bar-demo": E161,
  "announcement-bar-variants": E162,
  "empty-demo": E163,
  "progress-demo": E164,
  "progress-labeled": E165,
  "skeleton-demo": E166,
  "sonner-demo": E167,
  "spinner-demo": E168,
  "spinner-button": E169,
  "attachment-demo": E170,
  "attachment-states": E171,
  "bubble-demo": E172,
  "bubble-variants": E173,
  "bubble-reactions": E174,
  "marker-demo": E175,
  "message-demo": E176,
  "message-scroller-demo": E177,
};

export const blocks: Record<string, ComponentType> = {
  "dashboard": B0,
  "docs-layout": B1,
  "faq": B2,
  "feature-grid": B3,
  "footer": B4,
  "hero": B5,
  "login": B6,
  "not-found": B7,
  "pricing": B8,
  "settings": B9,
  "signup": B10,
};
