// Generated by scripts/build-registry.mjs. Do not edit.
import type { ComponentType } from "react";
import E0 from "@/registry/lantern/examples/eyebrow-demo";
import E1 from "@/registry/lantern/examples/navbar-demo";
import E2 from "@/registry/lantern/examples/stat-demo";
import E3 from "@/registry/lantern/examples/status-dot-demo";
import E4 from "@/registry/lantern/examples/terminal-demo";
import E5 from "@/registry/lantern/examples/button-demo";
import E6 from "@/registry/lantern/examples/button-variants";
import E7 from "@/registry/lantern/examples/button-sizes";
import E8 from "@/registry/lantern/examples/button-states";
import E9 from "@/registry/lantern/examples/checkbox-demo";
import E10 from "@/registry/lantern/examples/checkbox-disabled";
import E11 from "@/registry/lantern/examples/checkbox-checklist";
import E12 from "@/registry/lantern/examples/field-demo";
import E13 from "@/registry/lantern/examples/field-login";
import E14 from "@/registry/lantern/examples/field-signup";
import E15 from "@/registry/lantern/examples/field-settings";
import E16 from "@/registry/lantern/examples/field-contact";
import E17 from "@/registry/lantern/examples/field-newsletter";
import E18 from "@/registry/lantern/examples/input-demo";
import E19 from "@/registry/lantern/examples/input-types";
import E20 from "@/registry/lantern/examples/input-group-demo";
import E21 from "@/registry/lantern/examples/input-group-affixes";
import E22 from "@/registry/lantern/examples/input-group-button";
import E23 from "@/registry/lantern/examples/input-otp-demo";
import E24 from "@/registry/lantern/examples/input-otp-separator";
import E25 from "@/registry/lantern/examples/label-demo";
import E26 from "@/registry/lantern/examples/radio-group-demo";
import E27 from "@/registry/lantern/examples/radio-group-cards";
import E28 from "@/registry/lantern/examples/select-demo";
import E29 from "@/registry/lantern/examples/select-grouped";
import E30 from "@/registry/lantern/examples/select-states";
import E31 from "@/registry/lantern/examples/slider-demo";
import E32 from "@/registry/lantern/examples/slider-range";
import E33 from "@/registry/lantern/examples/switch-demo";
import E34 from "@/registry/lantern/examples/switch-settings";
import E35 from "@/registry/lantern/examples/textarea-demo";
import E36 from "@/registry/lantern/examples/textarea-states";
import E37 from "@/registry/lantern/examples/toggle-demo";
import E38 from "@/registry/lantern/examples/toggle-outline";
import E39 from "@/registry/lantern/examples/toggle-text";
import E40 from "@/registry/lantern/examples/toggle-group-demo";
import E41 from "@/registry/lantern/examples/toggle-group-multiple";
import E42 from "@/registry/lantern/examples/accordion-demo";
import E43 from "@/registry/lantern/examples/avatar-demo";
import E44 from "@/registry/lantern/examples/avatar-fallback";
import E45 from "@/registry/lantern/examples/avatar-group";
import E46 from "@/registry/lantern/examples/badge-demo";
import E47 from "@/registry/lantern/examples/card-demo";
import E48 from "@/registry/lantern/examples/card-art";
import E49 from "@/registry/lantern/examples/kbd-demo";
import E50 from "@/registry/lantern/examples/separator-demo";
import E51 from "@/registry/lantern/examples/table-demo";
import E52 from "@/registry/lantern/examples/table-compact";
import E53 from "@/registry/lantern/examples/alert-dialog-demo";
import E54 from "@/registry/lantern/examples/dialog-demo";
import E55 from "@/registry/lantern/examples/dialog-scrollable";
import E56 from "@/registry/lantern/examples/dropdown-menu-demo";
import E57 from "@/registry/lantern/examples/dropdown-menu-checkboxes";
import E58 from "@/registry/lantern/examples/dropdown-menu-radio-group";
import E59 from "@/registry/lantern/examples/hover-card-demo";
import E60 from "@/registry/lantern/examples/popover-demo";
import E61 from "@/registry/lantern/examples/sheet-demo";
import E62 from "@/registry/lantern/examples/sheet-sides";
import E63 from "@/registry/lantern/examples/tooltip-demo";
import E64 from "@/registry/lantern/examples/breadcrumb-demo";
import E65 from "@/registry/lantern/examples/breadcrumb-dropdown";
import E66 from "@/registry/lantern/examples/pagination-demo";
import E67 from "@/registry/lantern/examples/tabs-demo";
import E68 from "@/registry/lantern/examples/tabs-boxed";
import E69 from "@/registry/lantern/examples/alert-demo";
import E70 from "@/registry/lantern/examples/alert-variants";
import E71 from "@/registry/lantern/examples/empty-demo";
import E72 from "@/registry/lantern/examples/progress-demo";
import E73 from "@/registry/lantern/examples/progress-labeled";
import E74 from "@/registry/lantern/examples/skeleton-demo";
import E75 from "@/registry/lantern/examples/sonner-demo";
import E76 from "@/registry/lantern/examples/spinner-demo";
import E77 from "@/registry/lantern/examples/spinner-button";

export const examples: Record<string, ComponentType> = {
  "eyebrow-demo": E0,
  "navbar-demo": E1,
  "stat-demo": E2,
  "status-dot-demo": E3,
  "terminal-demo": E4,
  "button-demo": E5,
  "button-variants": E6,
  "button-sizes": E7,
  "button-states": E8,
  "checkbox-demo": E9,
  "checkbox-disabled": E10,
  "checkbox-checklist": E11,
  "field-demo": E12,
  "field-login": E13,
  "field-signup": E14,
  "field-settings": E15,
  "field-contact": E16,
  "field-newsletter": E17,
  "input-demo": E18,
  "input-types": E19,
  "input-group-demo": E20,
  "input-group-affixes": E21,
  "input-group-button": E22,
  "input-otp-demo": E23,
  "input-otp-separator": E24,
  "label-demo": E25,
  "radio-group-demo": E26,
  "radio-group-cards": E27,
  "select-demo": E28,
  "select-grouped": E29,
  "select-states": E30,
  "slider-demo": E31,
  "slider-range": E32,
  "switch-demo": E33,
  "switch-settings": E34,
  "textarea-demo": E35,
  "textarea-states": E36,
  "toggle-demo": E37,
  "toggle-outline": E38,
  "toggle-text": E39,
  "toggle-group-demo": E40,
  "toggle-group-multiple": E41,
  "accordion-demo": E42,
  "avatar-demo": E43,
  "avatar-fallback": E44,
  "avatar-group": E45,
  "badge-demo": E46,
  "card-demo": E47,
  "card-art": E48,
  "kbd-demo": E49,
  "separator-demo": E50,
  "table-demo": E51,
  "table-compact": E52,
  "alert-dialog-demo": E53,
  "dialog-demo": E54,
  "dialog-scrollable": E55,
  "dropdown-menu-demo": E56,
  "dropdown-menu-checkboxes": E57,
  "dropdown-menu-radio-group": E58,
  "hover-card-demo": E59,
  "popover-demo": E60,
  "sheet-demo": E61,
  "sheet-sides": E62,
  "tooltip-demo": E63,
  "breadcrumb-demo": E64,
  "breadcrumb-dropdown": E65,
  "pagination-demo": E66,
  "tabs-demo": E67,
  "tabs-boxed": E68,
  "alert-demo": E69,
  "alert-variants": E70,
  "empty-demo": E71,
  "progress-demo": E72,
  "progress-labeled": E73,
  "skeleton-demo": E74,
  "sonner-demo": E75,
  "spinner-demo": E76,
  "spinner-button": E77,
};
